### ISSUE TITLE
OOM ERROR WITH PYTORCH 0.3.1

### ISSUE THREAD

**Issue by mjenkins1992** [quark0/darts#18]
I see open issues relating to this but all with PyTorch 0.4

Does anyone have experience with this in PyTorch 0.3.1?

New PyTorch user so any assistance is much appreciated. 

Thanks!!

`Experiment dir : eval-EXP-20180717-093523
07/17 09:35:23 AM gpu device = 0
07/17 09:35:23 AM args = Namespace(arch='DARTS', auxiliary=False, auxiliary_weight=0.4, batch_size=96, cutout=False, cutout_length=16, data='../data', drop_path_prob=0.2, epochs=600, gpu=0, grad_clip=5, init_channels=36, layers=20, learning_rate=0.025, model_path='saved_models', momentum=0.9, report_freq=50, save='eval-EXP-20180717-093523', seed=0, weight_decay=0.0003)
108 108 36
108 144 36
144 144 36
144 144 36
144 144 36
144 144 36
144 144 72
144 288 72
288 288 72
288 288 72
288 288 72
288 288 72
288 288 72
288 288 144
288 576 144
576 576 144
576 576 144
576 576 144
576 576 144
576 576 144
07/17 09:35:25 AM param size = 3.169414MB
Files already downloaded and verified
Files already downloaded and verified
07/17 09:35:27 AM epoch 0 lr 2.500000e-02
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    main() 
  File "train.py", line 102, in main
    train_acc, train_obj = train(train_queue, model, criterion, optimizer)
  File "train.py", line 122, in train
    logits, logits_aux = model(input)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/SSD/MARK/darts/cnn/model.py", line 148, in forward
    s0 = s1 = self.stem(input)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518241081361/work/torch/lib/THC/generic/THCStorage.cu:58`

**Comment by quark0** [comment]
Do you have enough GPU memory? I'd first try smaller batch sizes and see if that works.

**Comment by mjenkins1992** [comment]
@quark0 Thank you for the reply. I have a Titan Xp with 10GB memory so I reduced the batch size and now I have the following error. I have CUDA 8 and CUDNN 7.0.5 installed. 

`Experiment dir : eval-EXP-20180717-115931
07/17 11:59:31 AM gpu device = 0
07/17 11:59:31 AM args = Namespace(arch='DARTS', auxiliary=False, auxiliary_weight=0.4, batch_size=8, cutout=False, cutout_length=16, data='../data', drop_path_prob=0.2, epochs=600, gpu=0, grad_clip=5, init_channels=36, layers=20, learning_rate=0.025, model_path='saved_models', momentum=0.9, report_freq=50, save='eval-EXP-20180717-115931', seed=0, weight_decay=0.0003)
108 108 36
108 144 36
144 144 36
144 144 36
144 144 36
144 144 36
144 144 72
144 288 72
288 288 72
288 288 72
288 288 72
288 288 72
288 288 72
288 288 144
288 576 144
576 576 144
576 576 144
576 576 144
576 576 144
576 576 144
07/17 11:59:34 AM param size = 3.169414MB
Files already downloaded and verified
Files already downloaded and verified
07/17 11:59:35 AM epoch 0 lr 2.500000e-02
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    main() 
  File "train.py", line 102, in main
    train_acc, train_obj = train(train_queue, model, criterion, optimizer)
  File "train.py", line 122, in train
    logits, logits_aux = model(input)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/SSD/MARK/darts/cnn/model.py", line 148, in forward
    s0 = s1 = self.stem(input)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/gecko/MARK/anaconda3/envs/darts/lib/python3.5/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR`

**Comment by mjenkins1992** [comment]
I fixed this with a reinstall of CUDA and CUDNN. Looks like the Python packages installed through conda were not sufficient.

**Comment by dragen1860** [comment]
Hi, you can try pytorch 1.0 version: https://github.com/dragen1860/DARTS-PyTorch
It works without OOM yet.
